### ISSUE TITLE
Kepek hivatkozzanak blogbejegyzesekre

### ISSUE THREAD

**Issue by 3n1k0** [3n1k0/anniekostolany.com#31]
Es lehessen oket kattintani

**Comment by andormade** [comment]
It's possible by wrapping the `<Photo />` tags with `<Link></Link>` tags.

Example:
`<Link to="/blog/2018/02/10/dutch-model-fall-photoshoot"><Photo file="" /></Link>`

Just don't forget to import Link: `import { Link } from 'react-router-dom';`
